name: Backlog Notification

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Backlog
        uses: bicstone/backlog-notify@master
        env:
          PROJECT_KEY: BACKLOG_PROJECT_ID
          API_HOST: tarosky.backlog.jp
          API_KEY: ${{ secrets.BACKLOG_API_KEY }}
